import type { SceneDefinition } from './types';

// A scene describes musical behaviour, not clock time. The same scene can
// later be selected by the clock, a Work/Sleep/Walk button or an external event.
export const SCENES: Record<string, SceneDefinition> = {
  'deep-night': {
    id: 'deep-night',
    name: 'Deep night',
    description: 'Long harmony, distant keys and extended silence.',
    progressionIds: ['nightFlow', 'quietRise', 'suspended'],
    chordHoldMs: { min: 13_800, max: 18_500 },
    transitionMs: { min: 4_800, max: 7_200 },
    padVelocity: { min: 0.24, max: 0.275 },
    keysVelocity: { min: 0.13, max: 0.19 },
    keysGapMs: { min: 3_400, max: 6_800 },
    keysRestMs: { min: 9_000, max: 17_000 },
    keysPhraseLength: { min: 1, max: 4 },
    keysEarlyRestChance: 0.3,
    keysDirectionChangeChance: 0.16,
    keysRegister: { min: 62, max: 79 },
  },
  dawn: {
    id: 'dawn',
    name: 'Dawn',
    description: 'Slow upward movement with a little more light.',
    progressionIds: ['quietRise', 'openSky', 'softSteps'],
    chordHoldMs: { min: 12_400, max: 16_400 },
    transitionMs: { min: 4_200, max: 6_200 },
    padVelocity: { min: 0.255, max: 0.29 },
    keysVelocity: { min: 0.145, max: 0.205 },
    keysGapMs: { min: 2_900, max: 5_700 },
    keysRestMs: { min: 7_600, max: 14_000 },
    keysPhraseLength: { min: 2, max: 4 },
    keysEarlyRestChance: 0.24,
    keysDirectionChangeChance: 0.19,
    keysRegister: { min: 64, max: 81 },
  },
  morning: {
    id: 'morning',
    name: 'Morning',
    description: 'Clear major harmony and gently active melodic fragments.',
    progressionIds: ['current', 'daylight', 'openSky', 'suspended'],
    chordHoldMs: { min: 10_800, max: 14_300 },
    transitionMs: { min: 3_600, max: 5_400 },
    padVelocity: { min: 0.27, max: 0.305 },
    keysVelocity: { min: 0.155, max: 0.22 },
    keysGapMs: { min: 2_400, max: 4_900 },
    keysRestMs: { min: 6_400, max: 11_800 },
    keysPhraseLength: { min: 2, max: 5 },
    keysEarlyRestChance: 0.2,
    keysDirectionChangeChance: 0.22,
    keysRegister: { min: 64, max: 83 },
  },
  daylight: {
    id: 'daylight',
    name: 'Daylight',
    description: 'Balanced movement for focus without rhythmic pressure.',
    progressionIds: ['current', 'daylight', 'softSteps', 'openSky'],
    chordHoldMs: { min: 10_200, max: 13_600 },
    transitionMs: { min: 3_400, max: 5_000 },
    padVelocity: { min: 0.275, max: 0.31 },
    keysVelocity: { min: 0.16, max: 0.225 },
    keysGapMs: { min: 2_200, max: 4_600 },
    keysRestMs: { min: 5_800, max: 10_800 },
    keysPhraseLength: { min: 2, max: 5 },
    keysEarlyRestChance: 0.18,
    keysDirectionChangeChance: 0.23,
    keysRegister: { min: 64, max: 83 },
  },
  afternoon: {
    id: 'afternoon',
    name: 'Afternoon',
    description: 'Open suspended harmony with wider, slower melodic curves.',
    progressionIds: ['suspended', 'openSky', 'current', 'evening'],
    chordHoldMs: { min: 11_200, max: 15_000 },
    transitionMs: { min: 3_800, max: 5_800 },
    padVelocity: { min: 0.265, max: 0.3 },
    keysVelocity: { min: 0.15, max: 0.215 },
    keysGapMs: { min: 2_600, max: 5_400 },
    keysRestMs: { min: 6_800, max: 12_600 },
    keysPhraseLength: { min: 2, max: 5 },
    keysEarlyRestChance: 0.22,
    keysDirectionChangeChance: 0.2,
    keysRegister: { min: 62, max: 81 },
  },
  evening: {
    id: 'evening',
    name: 'Evening',
    description: 'Warmer minor colour and more space between phrases.',
    progressionIds: ['evening', 'quietRise', 'nightFlow', 'suspended'],
    chordHoldMs: { min: 12_400, max: 16_800 },
    transitionMs: { min: 4_200, max: 6_500 },
    padVelocity: { min: 0.25, max: 0.29 },
    keysVelocity: { min: 0.14, max: 0.205 },
    keysGapMs: { min: 3_000, max: 6_000 },
    keysRestMs: { min: 7_800, max: 14_800 },
    keysPhraseLength: { min: 1, max: 4 },
    keysEarlyRestChance: 0.27,
    keysDirectionChangeChance: 0.18,
    keysRegister: { min: 62, max: 81 },
  },
  'late-night': {
    id: 'late-night',
    name: 'Late night',
    description: 'Sparse suspended harmony preparing the deep-night state.',
    progressionIds: ['nightFlow', 'evening', 'quietRise'],
    chordHoldMs: { min: 13_200, max: 18_000 },
    transitionMs: { min: 4_600, max: 7_000 },
    padVelocity: { min: 0.24, max: 0.28 },
    keysVelocity: { min: 0.13, max: 0.195 },
    keysGapMs: { min: 3_300, max: 6_600 },
    keysRestMs: { min: 8_800, max: 16_000 },
    keysPhraseLength: { min: 1, max: 4 },
    keysEarlyRestChance: 0.29,
    keysDirectionChangeChance: 0.16,
    keysRegister: { min: 62, max: 79 },
  },
};

export function findScene(sceneId: string): SceneDefinition {
  const scene = SCENES[sceneId];
  if (!scene) throw new Error(`Unknown generator scene: ${sceneId}`);
  return scene;
}
